### ISSUE TITLE
Keycloak SIngle Sign On not working in docker-compose

### ISSUE THREAD

**Issue by mattronix** [waldur/waldur-mastermind#48]
Cant seem to find how to login with single sign on on docker-compose, only local login button shows.

Despite keycloak section being present.

**Comment by livenson** [comment]
can you show content of your auth.yaml? just make sure no secret tokens are there
also check output from the initidb container, it might have hints why auth.yaml pre-configuration is not loaded

ps you can also add keycloak configuration via Homeport, by going to Administration / Settings / Identity providers.

**Comment by mattronix** [comment]
```
- provider: "keycloak"
  label: "Keycloak"
  client_id: "waldur"
  client_secret: "CHANGEME_KEYCLOAK_CLIENT_SECRET"
  discovery_url: "http://localhost/auth/realms/Waldur/.well-known/openid-configuration"
  management_url: ""
  protected_fields:
    - "full_name"
    - "email"
  ```
